### ISSUE TITLE
WebGPU support?

### ISSUE THREAD

**Issue by flatsiedatsie** [tangledgroup/llama-cpp-wasm#3]
Does this project use WebGPU acceleration?

**Comment by jpohhhh** [comment]
No, it's non-trivial to use/add graphics accelerators, ex. llama.cpp _just_ landed initial support for Vulkan nearly a year later. 

Dev pattern in llama.cpp for this seems to be you have to write shaders that are callable from the C++ code and add a compiler flag, a la how Metal and Vulkan are handled

**Comment by flatsiedatsie** [comment]
Thanks.
