### ISSUE TITLE
Embedding support

### ISSUE THREAD

**Issue by Mihaiii** [tangledgroup/llama-cpp-wasm#4]
Is there a chance to add support for [llama.cpp's embedding](https://github.com/ggerganov/llama.cpp/tree/master/examples/embedding)?

Thanks!

**Comment by flatsiedatsie** [comment]
Is this what you mean? https://github.com/ngxson/wllama

**Comment by Mihaiii** [comment]
@flatsiedatsie very cool, much wow. Thanks!
